# Travis CI script

language: c

os:
#   - linux
    - osx

osx_image: xcode7.3

script: ./.travis_build.sh

#   rm  -rf .travis_build.dir
#   mkdir   .travis_build.dir
#   cd      .travis_build.dir
#   cmake   ../ -DCMAKE_INSTALL_PREFIX=$HOME/noinst -DCMAKE_BUILD_TYPE=Release
#   make

